---
abstract: 'Subversion activity notification'
author:
  - 'David E. Wheeler <david@kineticode.com>'
build_requires:
  File::Spec: 0
  Module::Build: 0.2701
  Test::More: 0.17
configure_requires:
  Module::Build: 0.2701
dynamic_config: 1
generated_by: 'Module::Build version 0.3703, CPAN::Meta::Converter version 2.110440'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: SVN-Notify
provides:
  SVN::Notify:
    file: lib/SVN/Notify.pm
    version: 2.81
  SVN::Notify::Alternative:
    file: lib/SVN/Notify/Alternative.pm
    version: 1.0
  SVN::Notify::Filter::Trac:
    file: lib/SVN/Notify/Filter/Trac.pm
    version: 2.81
  SVN::Notify::HTML:
    file: lib/SVN/Notify/HTML.pm
    version: 2.81
  SVN::Notify::HTML::ColorDiff:
    file: lib/SVN/Notify/HTML/ColorDiff.pm
    version: 2.81
  SVN::Notify::SMTP:
    file: lib/SVN/Notify.pm
    version: 0
recommends:
  File::Spec: 0
  HTML::Entities: 0
  Net::SMTP: 0
  Net::SMTP_auth: 0
  Pod::Usage: 1.33
  Test::Pod: 1.41
  Test::Pod::Coverage: 1.06
  Text::Trac: 0.10
requires:
  Getopt::Long: 2.34
  perl: 5.006
resources:
  license: http://dev.perl.org/licenses/
version: 2.81
