---
name: SVN-Notify
version: 2.50
author:
  - David Wheeler <david@kineticode.com>
abstract: Subversion activity notification
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Getopt::Long: 2.34
recommends:
  HTML::Entities: 0
  Pod::Usage: 0
  Test::Pod: 1.2
  Test::Pod::Coverage: 1.06
build_requires:
  Module::Build: 0.26
  Test::Simple: 0.17
provides:
  SVN::Notify:
    file: lib/SVN/Notify.pm
    version: 2.50
  SVN::Notify::HTML:
    file: lib/SVN/Notify/HTML.pm
    version: 2.50
  SVN::Notify::HTML::ColorDiff:
    file: lib/SVN/Notify/HTML/ColorDiff.pm
    version: 2.50
generated_by: Module::Build version 0.2703
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
